### ISSUE TITLE
linuxmuster-webui7 1.0.41-1: config.yml does not exist

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-webui7#75] opened 2019-01-18 20:06 UTC
During setup version 1.0.41-1 produces following output:
```
File /etc/linuxmuster/webui/config.yml does not exist.
cp: cannot create regular file '/etc/linuxmuster/webui/config.yml': No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
Bundle certificate for webui
Run Sophomorix-UI to add permissions
* WebUI Setup Success!
```

**Comment by kiarn** [comment] 2019-01-19 23:23
Hello @HappyBasher !

What you are mentionning is weird : the file `/etc/linuxmuster/webui/config.yml` is in a test branch `config-linuxmuster` in which we are trying to split the config files.
This error is thrown through the file `/usr/lib/linuxmuster-webui/etc/create_aj_cfg.sh`, and this version should not be in the alpha-package yet.

**Comment by zefanja** [comment] 2019-01-20 00:28
I got the same error. Workaround is to create the file by yourself. 

> What you are mentionning is weird : the file /etc/linuxmuster/webui/config.yml is in a test branch config-linuxmuster in which we are trying to split the config files.
This error is thrown through the file /usr/lib/linuxmuster-webui/etc/create_aj_cfg.sh, and this version should not be in the alpha-package yet.

Looks like someone packaged exactly this branch for 1.0.41...

**Comment by PLanB2008** [comment] 2019-01-20 12:25
I fixed some issues in the testing branch and merged it to alpha branch from which on we build our packages.

The packages worked for me and I was able to login for new installations. I'll look into this tomorrow. I assume theres just a minor problem with the hook script we run on package upgrades.

**Comment by kiarn** [comment] 2019-01-20 12:37
The issue is following : postinst script does the job for a new install, but not split the actual config file for an existing installation. In any case of update without `/etc/linuxmuster/webui/config.yml`, this error will be thrown.

The question is : there is yet not so many existing installations of linuxmuster-webui7, and this error occurs because a major change in the config file behaviour, do we have to implement this in the postinst script ?

It would be easier to let the concerned person solve it with following hint : in an existing installation, the file `/etc/ajenti/config.yml` looks like : 

```
auth:
  allow_sudo: true
  emails: {}
  auth: lm
  users: null
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
linuxmuster:
  initialized: false
  is-configured: false
  ldap:
    binddn: CN=global-binduser,OU=Management,OU=GLOBAL,DC=linuxmuster,DC=lan
    bindpw: blablablablablabla
    host: server
    searchdn: DC=linuxmuster,DC=lan
  provision: false
color: default
language: de
max_sessions: 9
name: server.linuxmuster.lan
restricted_user: nobody
ssl:
  certificate: /ajenti.txt
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: true
```

It has to be split into : 

```
cat /etc/ajenti/config.yml
auth:
  allow_sudo: true
  emails: {}
  auth: lm
  users: null
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: default
language: de
max_sessions: 9
name: server.linuxmuster.lan
restricted_user: nobody
ssl:
  certificate: /ajenti.txt
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: true
```
and 

```
cat /etc/linuxmuster/webui/config.yml 
linuxmuster:
  initialized: false
  is-configured: false
  ldap:
    binddn: CN=global-binduser,OU=Management,OU=GLOBAL,DC=linuxmuster,DC=lan
    bindpw: blablablablablabla
    host: server
    searchdn: DC=linuxmuster,DC=lan
  provision: false
```
Or simply cut the linuxmuster part from the yaml in `/etc/linuxmuster/webui/config.yml`

**Comment by kiarn** [comment] 2019-01-20 13:54
This python script may eventually help : 

```
import yaml
import shutil
import os
import sys

path_ajenti  = '/etc/ajenti/config.yml'
path_webui   = '/etc/linuxmuster/webui/config.yml'
config_webui = {}

if not os.path.isfile(path_webui):
    try:
        ## Backup 
        shutil.copyfile(path_ajenti, path_ajenti + '.bak')

        ## Load existing config
        print("Load existing ajenti config file ...")
        with open(path_ajenti, 'r') as f:
            config_ajenti = yaml.load(f)
    except:
        print("Error loading ajenti config file ...")
        sys.exit()

    ## Copy linuxmuster config
    print("Copy linuxmuster config in /etc/linuxmuster/webui/config.yml ...")
    config_webui['linuxmuster'] = config_ajenti['linuxmuster']

    with open(path_webui, 'w') as f:
        yaml.dump(config_webui, f, default_flow_style=False)

    ## Update ajenti config
    print("Update ajenti config ...")
    del config_ajenti['linuxmuster']

    with open(path_ajenti, 'w') as f:
        yaml.dump(config_ajenti, f, default_flow_style=False)

    print("Finished!")
else:
    print("Config files for WebUI are already ok!")
```

It's easier to parse yml with python as with bash ...

**Comment by zefanja** [comment] 2019-01-20 22:24
For me it was fine to create/touch the file (empty) and the folder and re-run the setup / reconfigure webui.

**Comment by kiarn** [comment] 2019-01-20 22:35
The goal is to hide the special data from linuxmuster config ( bindpw, ... ), which appear on the source code from any page.
With a touch of an empty config file, this may let the setup run fine, but your bindpw will in the future update of ajenti again appear on the default page.

**Comment by zefanja** [comment] 2019-01-20 22:38
Aren't the config files re-created on every setup? AFAIK the bindpw is not in the source code anymore on my test-system.

**Comment by kiarn** [comment] 2019-01-20 22:44
> AFAIK the bindpw is not in the source code anymore on my test-system.

I did a patch in the postinst process for this, but this was not a good solution, we have to split the config ajenti/linuxmuster for more security and flexibility.
As I said, the next update of ajenti will erase this patch, and if the linuxmuster dict is still in `/etc/ajenti/config.yml`, it will appear on the source code.

**Comment by PLanB2008** [comment] 2019-01-21 08:48
> The issue is following : postinst script does the job for a new install, but not split the actual config file for an existing installation. 

Thats right, I didn't pay attention to this, my bad. I dont think there are that many installation out there currently. If your python script work, and we have a safe way to determine if we have to update an old installation we could implement it.

On the other hand it isn't a big hassle to split the information by hand for these few installations. Focus is a safe and clean installation for beta testing, so it was necessary to implement this quick.

@kiarn what do you think, should we look for the file /etc/linuxmuster/webui/config.yml and run the python script if file is not found?

**Comment by kiarn** [comment] 2019-01-21 09:10
> > The issue is following : postinst script does the job for a new install, but not split the actual config file for an existing installation.
> 
> Thats right, I didn't pay attention to this, my bad. I dont think there are that many installation out there currently. If your python script work, and we have a safe way to determine if we have to update an old installation we could implement it.
> 
> On the other hand it isn't a big hassle to split the information by hand for these few installations. Focus is a safe and clean installation for beta testing, so it was necessary to implement this quick.
> 
> @kiarn what do you think, should we look for the file /etc/linuxmuster/webui/config.yml and run the python script if file is not found?

Yep, I would do so. In case of an empty ` /etc/linuxmuster/webui/config.yml`, it will not work.
I pushed right now the python script with little modifications.
It worked on my test server, I hope it will work overall.

Merge alpha + config_linuxmuster ?

**Comment by PLanB2008** [comment] 2019-01-21 15:28
Okay I merged the changes back to alpha branch and uploaded a new debian package. (linuxmuster-webui7_1.0.42)
@zefanja could you please check if this works for your installation? (You should delete your empty /etc/linuxmuster/webui/config.yml first)

**Comment by kiarn** [comment] 2019-01-21 17:47
> Okay I merged the changes back to alpha branch and uploaded a new debian package. (linuxmuster-webui7_1.0.42)

Ok, thanks. Can I now delete the branch config-linuxmuster ?

**Comment by zefanja** [comment] 2019-01-22 05:37
Now I get this error:

```
Load existing ajenti config file ...
Copy linuxmuster config in /etc/linuxmuster/webui/config.yml ...
Traceback (most recent call last):
  File "/usr/lib/linuxmuster-webui/etc/split_config_aj.py", line 30, in <module>
    config_webui['linuxmuster'] = config_ajenti['linuxmuster']
KeyError: 'linuxmuster'
```

**Comment by kiarn** [comment] 2019-01-22 06:27
Is the linuxmuster part still written in `/etc/ajenti/config.yml` ?

**Comment by zefanja** [comment] 2019-01-22 07:35
No

**Comment by kiarn** [comment] 2019-01-22 08:05
That's the reason : if the config file from ajenti does not contain the linuxmuster part, it can not create the new config file.

**Comment by PLanB2008** [comment] 2019-01-22 17:16
> > Okay I merged the changes back to alpha branch and uploaded a new debian package. (linuxmuster-webui7_1.0.42)
> 
> Ok, thanks. Can I now delete the branch config-linuxmuster ?

I'll delete it :)

**Closed as completed** 2019-02-23 10:11 UTC
