### ISSUE TITLE
Error in WebUI after setup "Server error: POST /api/lmn/quota"

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-webui7#108] opened 2019-07-24 06:27 UTC
After first setting up the system (without docker, opsi and mail server) on login the secure WebUI a Server error (SyntaxError on Request POST /api/lmn/quota, invalid syntax (<unknown>,line 1) is displayed:

![Bildschirmfoto 2019-07-24 um 08 22 54](https://user-images.githubusercontent.com/48863382/61769933-3edbf380-adec-11e9-8750-b4a103b96d7b.png)

Here the traceback:
[Traceback.txt](https://github.com/linuxmuster/linuxmuster-webui7/files/3425290/Traceback.txt)

**Comment by PLanB2008** [comment] 2019-07-24 06:58
Well this is due Error Output in the communication between sophomorix and webui. In This case its caused by the quotabar you see after login.
@kiarn works on this in general. But in this case it seems to happen to be an sophomorix4 issue wehre @jeffbeck is responsible for.

What happens if you enter 

    sophomorix-query --sam global-admin --user-full --quota-usage -j

(Assuming you login as global-admin, otherwise change the user to reflect your used userprofile)
Can you provide the output?

**Comment by RolandBBerlin** [comment] 2019-07-24 07:48
Here the output:
![Bildschirmfoto 2019-07-24 um 09 48 09](https://user-images.githubusercontent.com/48863382/61774902-270a6c80-adf8-11e9-890c-88bff44efcb9.png)

**Comment by kiarn** [comment] 2019-07-24 15:45
Hello @RolandBBerlin 

Please recheck with global-admin and not global_admin.

**Comment by RolandBBerlin** [comment] 2019-07-24 17:22
Sorry ;-), here the output as a file

[sophomorix global-admin output.txt](https://github.com/linuxmuster/linuxmuster-webui7/files/3428052/sophomorix.global-admin.output.txt)

**Comment by kiarn** [comment] 2019-07-24 21:31
This commit https://github.com/linuxmuster/linuxmuster-webui7/commit/caec565ad0101b1bde527113b5b27e3baf786659 fixs this problems, but does not solves the fact that something is wrong with perl or with sophomorix configuration.

**Comment by PLanB2008** [comment] 2019-08-06 12:03
So we gonna close the issue.

**Closed as completed by PLanB2008** 2019-08-06 12:03 UTC
