### ISSUE TITLE
Performance enhancement when setting/unsetting participants in exam mode

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#255] opened 2022-12-02 14:19 UTC
When setting users in exam mode the teacher puts tickmarks at the doctors hat behind a user.
When saving this settings, sophomorix-exam is called with EVERY user with such a tickmark, even if some users are already in exam mode.

Performace of sophomorix-exam is slow because exam mode involves: creating a user, creating directories and setting acls 
(i.e. 3 seconds per user)

If sophomorix is called ONLY with users where the exam mode must be CHANGED (yellow tickmark boxes), performance would be enhanced.

If sophomorix must make sure that EVERY user is in exam mode, it has to make sure the account exists, make sure that directories exist, ... this takes almost the same amount of time as setting exam mode. 

This is especially true, when one user arrives late for an exam. Instead of setting one user in exam mode i.e. 10 users must be checked which multipiles the amount of time.

Maybe the EVERY user list is only created by clicking on the column head of 'doctors hat', which means 'select all'

Unsetting an exam is accordingly

**Comment by kiarn** [comment] 2022-12-03 11:35
Hello @jeffbeck 

I cannot confirm this : if the participants list change, then `sophomorix-exam-mode` should only be called with the users that are actually not in exam mode. 
The test is written here : 

https://github.com/linuxmuster/linuxmuster-webui7/blob/6da543650cc1fb35c7bebe9eccbcf3e8e0179e32/usr/lib/linuxmuster-webui/plugins/lmn_session/views.py#L155

and this test will filter the user list to only keep users that are not in exam mode.
I've just tested on my server, and I was not able to reproduce what you mean.

Arnaud

**Comment by kiarn** [comment] 2023-04-18 16:12
Since we are planning to run the exam mode only for full sessions, I can close this issue.

**Closed as completed by kiarn** 2023-04-18 16:12 UTC
