### ISSUE TITLE
Removing teachers from class -> project not found

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-webui7#151] opened 2020-08-12 20:12 UTC
Removing teacher from a class in the webui results in an error message saying that the project p_10b could not be found.
see screenshot...
this seems to be a bug...
![Screenshot_20200812_220734](https://user-images.githubusercontent.com/2824334/90062952-d73f6180-dce8-11ea-8093-0f1cb22548dc.png)

**Comment by kiarn** [comment] 2020-09-03 12:45
Hello,

The name of the project you are showing ( 10b migrated )does not seem to respect the name scheme of a project, i.e. 'p_SOMENAME', that's the reason.

How did you create this project ?

Arnaud

**Comment by jolly-jump** [comment] 2020-09-04 07:28
Hi, 
this is *not* a project.
This is me trying to remove teachers from a *class*!
Tobias

**Comment by jolly-jump** [comment] 2020-09-04 07:43
The class is named "10b migrated" because it was migrated from 6.2.

**Comment by kiarn** [comment] 2020-09-04 20:28
Ok, got it, I didn't pay enough attention to the screenshot.
https://github.com/linuxmuster/linuxmuster-webui7/commit/7c5eeec75162efb3fd39542975b63f73e243e182 solves this partially, because I'm not able to create a class with a space ( how to do this @jeffbeck ? ), and I think that this space in the name will cause further errors.

**Comment by jolly-jump** [comment] 2020-09-04 21:22
I am not sure, what the name is, the class was called "10b", but somewhere there is a "displayname" "10b migrated" which came obviously from the migration...

**Comment by kiarn** [comment] 2020-09-04 21:55
Maybe you can view it with `sophomorix-class -i`.

**Comment by jolly-jump** [comment] 2020-09-05 21:14
Thanks you are right.
Class name was "10b", Class description was "10b migrated". Anyway, the system removed those already anyway.

**Comment by kiarn** [comment] 2021-06-11 07:47
Hello @jolly-jump ,

I've just tested this with the last testing and master versions since the changes last month, and it seems that it now works, I can not reproduce it anymore with a `10b migrated` class, so I suggest to close this issue.

Feel free to comment it, we can reopen if you still have this issue.

**Closed as completed by kiarn** 2021-06-11 07:47 UTC
Labels: Sophomorix issue
