### ISSUE TITLE
"Finish" - button is not displayed, after setup is done

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#155] opened 2020-09-18 00:36 UTC
When I run the initial configuration in the webUI, after the linuxmuster-setup script is done, the Finish button is not displayed. I have to reload the page finish the setup.

**Comment by zefanja** [comment] 2020-09-19 05:50
![Peek 2020-09-19 12-47](https://user-images.githubusercontent.com/708888/93660215-a0423580-fa76-11ea-9b9e-ec949ccf8f92.gif)

**Comment by kiarn** [comment] 2021-02-13 10:13
Hello @zefanja 

Is this issue still valid ?
I know my answer is really, really late, but I was not able to reproduce this. I have tested it again this week with a new install and firefox as browser, without problem. Did you have some errors during the provisioning ? 

Arnaud

**Comment by kiarn** [comment] 2021-05-14 09:24
I tried again without problem. So I suggest to close this for the moment. If we get more details or if it occurs again we can still reopen it.

**Closed as completed by kiarn** 2021-05-14 09:24 UTC
