### ISSUE TITLE
Error after setup: plugin failed to load 

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#82] opened 2019-02-21 13:08 UTC
When I finished the setup, and click "Close" on the last dialog, I get this error (otherwise blank page):

```
Warning
The following plugin has failed to load: . Please fix or uninstall it.
OK
```
The console logs: 
```
ReferenceError: angular is not defined[Weitere Informationen] done:177:13

    <anonym> https://192.168.56.50:8080/view/lm/init/done:177 
```

**Comment by kiarn** [comment] 2019-03-25 15:56
Hello @zefanja,

There's many possible reasons for this. But first : what browser did you use for this test ?

**Comment by kiarn** [comment] 2019-05-13 10:20
I think it's due to a certificate error, when `/etc/ajenti/config.yml` includes `/etc/linuxmuster/ssl/server.cert.bundle.pem`
I'm working with domain and a let's encrypt cert, that's why I didn't see it.

Can you please confirm this ?

**Comment by zefanja** [comment] 2019-05-13 11:50
Yes, I'm using the default self signed cert. I will test further.

**Comment by kiarn** [comment] 2019-05-13 15:00
If you are using Chrome, there are some caching problems with SSL certificates that are self-signed.
I tried with the default certificate from linuxmuster.net : in a normal window, I get this error too, but in a private window, the webui just commes fine.

So, the possible solutions are : 

1) not using chrome in normal mode
2) use a valid certificate

**Comment by zefanja** [comment] 2019-05-13 15:15
I use Firefox. 

What do you mean with "I tried with the default certificate from linuxmuster.net"? Do you mean the self signed cert that is created during linuxmuster-setup?

**Comment by kiarn** [comment] 2019-05-13 17:41
Yes, that's what I meant.
After restart, no more error in Chrome, I didn't succeed to reproduce this error with Firefox.

**Comment by kiarn** [comment] 2020-02-24 13:30
I think we can close this issue, I don't remember seeing other problems in this form this year, and without details it will difficult to debug.
We can reopen it if it occurs again.

**Closed as completed by kiarn** 2020-02-24 13:30 UTC
